### ISSUE TITLE
Accent menu opens every time I hold a key down

### ISSUE THREAD

**Issue by davidburke2500** [robotboy655/gmod-lua-menu#51]
Whenever I hold any key down, the keyboard accent menu opens in the top left of the screen.
I have the newest version downloaded, and I also just re-installed Garry's Mod. I'm on MacOS Ventura 13.1 fwiw.
Can anyone help me out here? It's super distracting lmao

[I also can't see my saves or dupes](https://imgur.com/a/zLruY2M)
[Here's a video of the accent menu opening](https://imgur.com/a/7ZjvuKp)

**Comment by robotboy655** [comment]
I don't know why you post this here, neither of these issues appear to be related to this addon.

The dupes/saves thing is because you do not have the HTML engine working, which I imagine is why you downloaded this mod. This is a duplicate report from https://github.com/robotboy655/gmod-lua-menu/issues/29

The "accent menu" I have never seen before, and I don't think it comes from this mod.
