### ISSUE TITLE
Mounted games are listed in GAMEMODES section of New Games menu.

### ISSUE THREAD

**Issue by zerfgog** [robotboy655/gmod-lua-menu#6]
![ayy](http://i.imgur.com/PLlR90N.png)

**Comment by robotboy655** [comment]
The fact that they are listed in GAMEMODES section is because that's what the default Garry's Mod list does ( and I have no plans of changing that yet )
The fact that you have Team Fortress 2 and Portal maps only in GAMEMODES section can be caused by these things:
* You not running latest version of the menu or running an edited version
* You do not have those games actually mounted, and only have maps that match the filters ( Which is exactly why I added the GAMES section )
